### ISSUE TITLE
Windows Defender detect Kitty contain Trojan:Win32/Zpevdo.B

### ISSUE THREAD

**Issue by azzizkusumah** [portapps/kitty-portable#34]
After install Kitty portable, then Windows Defender pop up with Trojan:Win32/Zpevdo.B .

workaround please.

Thank you

**Comment by crazy-max** [comment]
Sometimes Antivirus scanner reports that a program is infected with a Virus or Trojan, even when the program is not really infected with any malicious code. This kind of problem is known as "False Positive". In other words, [Antivirus companies cause a big headache to small developers](http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/).

As stipulated in the [FAQ](https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper), those detections are generic. Most likely based on a heuristic detection and more prone to be false-positive and this [happens quite often](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20antivirus) with programs written in [Golang](https://golang.org/). The best you can do is to report this to your Antivirus software vendor as a false positive.

See also portapps/portapps#68 and https://github.com/search?q=org%3Aportapps+antivirus&type=Issues. Thanks for your support.
